name: 'Node.js Package'
inputs:
  github_token:
    description: 'The GitHub token to use for authentication'
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@naya-01'
      - run: npm install
        shell: bash
      - run: npm publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ inputs.github_token }}